### signup route test
POST http://localhost:5000/auth/signup
Content-Type: application/json

{
    "firstName": "carlos",
    "lastName": "park",
    "email": "cpark@gmail.com",
    "password": "1111",
    "confirmPassword": "1111",
    "id": 3

}
### test login auth route
POST http://localhost:5000/auth/login
Content-Type: application/json

{
    "email": "cpark@gmail.com",
    "password": "1111"  
}

### test request get all posts
GET http://localhost:5000/posts/statistics


###Get posts by country  
GET http://localhost:5000/posts/statistics/search?country=China


###Get posts by Continent
GET http://localhost:5000/posts/statistics/continent?continent=Africa

###GET sync, overwrites DB by sync with latest data 
GET http://localhost:5000/posts/sync 


